# 기본 설정

In [ ]:
import pandas as pd

In [ ]:
# variable.csv : shop ~ car  값을 면적으로 나눈 값
df = pd.read_csv('/content/drive/MyDrive/비없비/지수/variable.csv', index_col = 0)
df

                      shop      park         trail  ...  re_center  vinyl  budget
부산광역시 강서구     1.101956e-08  0.006485  8.198551e-07  ...          1      2   0.049
부산광역시 금정구     1.532285e-07  0.035794  4.891054e-06  ...          1      2   0.035
부산광역시 기장군     2.290469e-08  0.039752  2.064171e-06  ...          1      2   0.038
부산광역시 남구      3.728660e-07  0.064748  6.126189e-06  ...          1      2   0.039
부산광역시 동구      2.027447e-07  0.098874  3.497347e-06  ...          1      2   0.043
부산광역시 동래구     6.012755e-07  0.251016  5.519709e-06  ...          1      2   0.038
부산광역시 부산진구    6.741375e-07  0.156921  2.083085e-06  ...          1      2   0.031
부산광역시 북구      1.778016e-07  0.023409  2.331741e-06  ...          1      2   0.028
부산광역시 사상구     5.539989e-08  0.019532  1.878056e-06  ...          1      2   0.034
부산광역시 사하구     4.788025e-08  0.012565  1.659577e-05  ...          1      2   0.036
부산광역시 서구      2.866093e-07  0.217234  1.037526e-05  ...          1      2   0.060
부산광역시 수영구     4.014608e-06  0.012493  7.402546e-06  ...          1      2   0.038
부산광역시 연제구     5.785347e-07  0.006349  1.002725e-05  ...          1      2   0.035
부산광역시 영도구     7.042354e-08  0.180124  9.549432e-06  ...          1      2   0.028
부산광역시 중구      2.477183e-06  0.106183  2.236543e-05  ...          1      2   0.042
부산광역시 해운대구    6.213260e-07  0.056219  3.564858e-06  ...          1      2   0.042
서울특별시 강남구     3.746740e-06  0.054343  5.835800e-06  ...          1      2   0.081
서울특별시 강동구     1.341983e-06  0.078689  9.715955e-06  ...          1      2   0.056
서울특별시 강북구     8.050726e-07  0.066403  1.894548e-05  ...          1      0   0.060
서울특별시 강서구     7.963927e-07  0.077449  5.513933e-06  ...          1      1   0.053
서울특별시 관악구     1.555665e-06  0.014970  7.203403e-06  ...          1      2   0.047
서울특별시 광진구     2.402868e-06  0.002704  7.873204e-06  ...          1      2   0.049
서울특별시 구로구     5.964241e-07  0.134536  2.487089e-06  ...          0      2   0.050
서울특별시 금천구     1.920086e-06  0.011436  1.988902e-05  ...          0      2   0.055
서울특별시 노원구     1.721333e-06  0.390712  1.321137e-05  ...          1      0   0.045
서울특별시 도봉구     6.779306e-07  0.480136  5.386643e-06  ...          1      2   0.034
서울특별시 동대문구    3.235876e-06  0.051903  3.807079e-06  ...          1      2   0.059
서울특별시 동작구     2.201299e-06  0.154129  1.246302e-05  ...          0      0   0.064
서울특별시 마포구     4.276666e-06  0.045960  1.386898e-05  ...          0      2   0.066
서울특별시 서대문구    3.744390e-06  0.077765  7.244827e-06  ...          1      2   0.063
서울특별시 서초구     1.532519e-06  0.035767  4.916831e-06  ...          1      2   0.071
서울특별시 성동구     2.490955e-06  0.035385  1.238360e-06  ...          1      2   0.048
서울특별시 성북구     2.400635e-06  0.045436  6.445094e-06  ...          1      2   0.050
서울특별시 송파구     2.332275e-06  0.108518  1.114709e-05  ...          1      2   0.057
서울특별시 양천구     9.192384e-07  0.129745  1.352429e-06  ...          1      0   0.042
서울특별시 영등포구    2.321963e-06  0.010148  1.627818e-06  ...          1      2   0.064
서울특별시 용산구     3.750089e-06  0.022924  4.887007e-06  ...          1      2   0.078
서울특별시 은평구     1.245334e-06  0.071357  1.266606e-05  ...          1      2   0.065
서울특별시 종로구     4.056342e-06  0.075714  4.265641e-05  ...          0      2   0.073
서울특별시 중구      6.626301e-06  0.023918  1.460196e-05  ...          1      2   0.081
서울특별시 중랑구     1.297572e-06  0.212080  6.140760e-06  ...          1      0   0.048
제주특별자치도 서귀포시  2.868480e-08  0.003053  2.539924e-06  ...          1      2   0.120
제주특별자치도 제주시   8.583082e-08  0.007252  1.708238e-06  ...          1      2   0.120

[43 rows x 11 columns]

In [ ]:
df.shape

(43, 11)

# min-max scaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler
# 객체 생성
minmax_scaler = MinMaxScaler()
# 분포 저장
minmax_scaler.fit(df)
# 스케일링
df_minmax_scaled = minmax_scaler.transform(df)

In [ ]:
df_minmax_scaled = pd.DataFrame(df_minmax_scaled)
df_minmax_scaled

          0         1         2         3   ...        7    8    9         10
0   0.000000  0.007919  0.000000  0.013032  ...  1.000000  1.0  1.0  0.228261
1   0.021497  0.069308  0.097312  0.077355  ...  0.970149  1.0  1.0  0.076087
2   0.001797  0.077597  0.029742  0.039505  ...  0.465672  1.0  1.0  0.108696
3   0.054699  0.129952  0.126835  0.231903  ...  0.916418  1.0  1.0  0.119565
4   0.028982  0.201432  0.063999  0.226015  ...  0.841791  1.0  1.0  0.163043
5   0.089226  0.520099  0.112338  0.280651  ...  0.811940  1.0  1.0  0.108696
6   0.100240  0.323012  0.030194  0.032459  ...  0.847761  1.0  1.0  0.032609
7   0.025212  0.043367  0.036138  0.149573  ...  0.889552  1.0  1.0  0.000000
8   0.006709  0.035247  0.025294  0.089663  ...  0.934328  1.0  1.0  0.065217
9   0.005572  0.020655  0.377085  0.047520  ...  0.940299  1.0  1.0  0.086957
10  0.041660  0.449342  0.228398  0.348989  ...  0.776119  1.0  1.0  0.347826
11  0.605203  0.020503  0.157343  0.316792  ...  0.949254  1.0  1.0  0.108696
12  0.085789  0.007635  0.220080  0.181877  ...  0.982090  1.0  1.0  0.076087
13  0.008980  0.371612  0.208659  0.176777  ...  0.967164  1.0  1.0  0.000000
14  0.372798  0.216741  0.514994  1.000000  ...  0.414925  1.0  1.0  0.152174
15  0.092257  0.112089  0.065613  0.183210  ...  0.680597  1.0  1.0  0.152174
16  0.564711  0.108159  0.119894  0.187395  ...  0.194030  1.0  1.0  0.576087
17  0.201195  0.159153  0.212639  0.322566  ...  0.447761  1.0  1.0  0.304348
18  0.120033  0.133419  0.433248  0.315239  ...  0.519403  1.0  0.0  0.347826
19  0.118721  0.156555  0.112200  0.267431  ...  0.656716  1.0  0.5  0.271739
20  0.233496  0.025691  0.152583  0.192048  ...  0.585075  1.0  1.0  0.206522
21  0.361564  0.000000  0.168593  0.371902  ...  0.698507  1.0  1.0  0.228261
22  0.088493  0.276127  0.039851  0.497538  ...  0.000000  0.0  1.0  0.239130
23  0.288584  0.018290  0.455801  0.349145  ...  0.498507  0.0  1.0  0.293478
24  0.258540  0.812697  0.296189  0.215118  ...  0.388060  1.0  0.0  0.184783
25  0.100814  1.000000  0.109158  0.313188  ...  0.346269  1.0  1.0  0.065217
26  0.487486  0.103048  0.071402  0.496362  ...  0.602985  1.0  1.0  0.336957
27  0.331094  0.317166  0.278301  0.460655  ...  0.564179  0.0  0.0  0.391304
28  0.644817  0.090600  0.311907  0.311799  ...  0.223881  0.0  1.0  0.413043
29  0.564355  0.157217  0.153573  0.264076  ...  0.256716  1.0  1.0  0.380435
30  0.229998  0.069252  0.097928  0.166249  ...  0.191045  1.0  1.0  0.467391
31  0.374880  0.068452  0.010003  0.306609  ...  0.516418  1.0  1.0  0.217391
32  0.361227  0.089503  0.134458  0.411815  ...  0.650746  1.0  1.0  0.239130
33  0.350893  0.221631  0.246847  0.344956  ...  0.668657  1.0  1.0  0.315217
34  0.137291  0.266092  0.012730  0.461059  ...  0.376119  1.0  0.0  0.152174
35  0.349334  0.015591  0.019312  0.281990  ...  0.340299  1.0  1.0  0.391304
36  0.565217  0.042352  0.097215  0.225764  ...  0.379104  1.0  1.0  0.543478
37  0.186585  0.143796  0.283154  0.406421  ...  0.253731  1.0  1.0  0.402174
38  0.611512  0.152922  1.000000  0.205330  ...  0.364179  0.0  1.0  0.489130
39  1.000000  0.044433  0.329427  0.325147  ...  0.053731  1.0  1.0  0.576087
40  0.194482  0.438545  0.127183  0.451322  ...  0.450746  1.0  0.0  0.217391
41  0.002670  0.000731  0.041114  0.000000  ...  0.471642  1.0  1.0  1.000000
42  0.011309  0.009525  0.021235  0.004949  ...  0.214925  1.0  1.0  1.000000

[43 rows x 11 columns]

In [ ]:
df_minmax_scaled.min()

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
dtype: float64

In [ ]:
df_minmax_scaled.max()

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
dtype: float64

# 카테고리 별 통합
- 한 카테고리 내 두개 이상의 값이 있을 때 평균 값을 지수로 계산
- 단일 값인 경우 그대로 사용

In [ ]:
# 컬럼 명 표시
df_minmax_scaled.columns = ['shop', 'park', 'trail', 'library', 'book', 'bike', 'car', 'recycle_rate', 're_center', 'vinyl', 'budget']
df_minmax_scaled.head()

       shop      park     trail  ...  re_center  vinyl    budget
0  0.000000  0.007919  0.000000  ...        1.0    1.0  0.228261
1  0.021497  0.069308  0.097312  ...        1.0    1.0  0.076087
2  0.001797  0.077597  0.029742  ...        1.0    1.0  0.108696
3  0.054699  0.129952  0.126835  ...        1.0    1.0  0.119565
4  0.028982  0.201432  0.063999  ...        1.0    1.0  0.163043

[5 rows x 11 columns]

In [ ]:
# df_new 테이블 생성
df_new = df_minmax_scaled
df_new.head(2)

       shop      park     trail  ...  re_center  vinyl    budget
0  0.000000  0.007919  0.000000  ...        1.0    1.0  0.228261
1  0.021497  0.069308  0.097312  ...        1.0    1.0  0.076087

[2 rows x 11 columns]

In [ ]:
# green 행 추가
df_new['green'] = (df_new['park'] + df_new['trail']) / 2
df_new.head()

       shop      park     trail   library  ...  re_center  vinyl    budget     green
0  0.000000  0.007919  0.000000  0.013032  ...        1.0    1.0  0.228261  0.003959
1  0.021497  0.069308  0.097312  0.077355  ...        1.0    1.0  0.076087  0.083310
2  0.001797  0.077597  0.029742  0.039505  ...        1.0    1.0  0.108696  0.053670
3  0.054699  0.129952  0.126835  0.231903  ...        1.0    1.0  0.119565  0.128394
4  0.028982  0.201432  0.063999  0.226015  ...        1.0    1.0  0.163043  0.132715

[5 rows x 12 columns]

In [ ]:
# share 행 추가
df_new['share'] = (df_new['library'] + df_new['book']) / 2
df_new.head()

       shop      park     trail   library  ...  vinyl    budget     green     share
0  0.000000  0.007919  0.000000  0.013032  ...    1.0  0.228261  0.003959  0.012744
1  0.021497  0.069308  0.097312  0.077355  ...    1.0  0.076087  0.083310  0.047338
2  0.001797  0.077597  0.029742  0.039505  ...    1.0  0.108696  0.053670  0.021047
3  0.054699  0.129952  0.126835  0.231903  ...    1.0  0.119565  0.128394  0.137024
4  0.028982  0.201432  0.063999  0.226015  ...    1.0  0.163043  0.132715  0.113008

[5 rows x 13 columns]

In [ ]:
# trans 행 추가
df_new['trans'] = (df_new['bike'] + df_new['car']) / 2
df_new.head()

       shop      park     trail  ...     green     share     trans
0  0.000000  0.007919  0.000000  ...  0.003959  0.012744  0.007169
1  0.021497  0.069308  0.097312  ...  0.083310  0.047338  0.069185
2  0.001797  0.077597  0.029742  ...  0.053670  0.021047  0.009582
3  0.054699  0.129952  0.126835  ...  0.128394  0.137024  0.001632
4  0.028982  0.201432  0.063999  ...  0.132715  0.113008  0.018342

[5 rows x 14 columns]

In [ ]:
# recycle 행 추가
df_new['recycle'] = (df_new['recycle_rate'] + df_new['re_center'] + df_new['vinyl']) / 3
df_new.head()

       shop      park     trail  ...     share     trans   recycle
0  0.000000  0.007919  0.000000  ...  0.012744  0.007169  1.000000
1  0.021497  0.069308  0.097312  ...  0.047338  0.069185  0.990050
2  0.001797  0.077597  0.029742  ...  0.021047  0.009582  0.821891
3  0.054699  0.129952  0.126835  ...  0.137024  0.001632  0.972139
4  0.028982  0.201432  0.063999  ...  0.113008  0.018342  0.947264

[5 rows x 15 columns]

In [ ]:
# 필요 없는 행 drop
df_new = df_new.drop(columns = ['park', 'trail', 'library', 'book', 'bike', 'car', 'recycle_rate', 're_center', 'vinyl'])
df_new

        shop    budget     green     share     trans   recycle
0   0.000000  0.228261  0.003959  0.012744  0.007169  1.000000
1   0.021497  0.076087  0.083310  0.047338  0.069185  0.990050
2   0.001797  0.108696  0.053670  0.021047  0.009582  0.821891
3   0.054699  0.119565  0.128394  0.137024  0.001632  0.972139
4   0.028982  0.163043  0.132715  0.113008  0.018342  0.947264
5   0.089226  0.108696  0.316219  0.174307  0.029428  0.937313
6   0.100240  0.032609  0.176603  0.025754  0.001022  0.949254
7   0.025212  0.000000  0.039752  0.081964  0.009709  0.963184
8   0.006709  0.065217  0.030270  0.044832  0.001586  0.978109
9   0.005572  0.086957  0.198870  0.050820  0.114819  0.980100
10  0.041660  0.347826  0.338870  0.174494  0.007481  0.925373
11  0.605203  0.108696  0.088923  0.269073  0.050887  0.983085
12  0.085789  0.076087  0.113858  0.137648  0.056283  0.994030
13  0.008980  0.000000  0.290135  0.088388  0.203080  0.989055
14  0.372798  0.152174  0.365867  1.000000  0.115747  0.804975
15  0.092257  0.152174  0.088851  0.130012  0.009616  0.893532
16  0.564711  0.576087  0.114026  0.129466  0.324299  0.731343
17  0.201195  0.304348  0.185896  0.195757  0.371341  0.815920
18  0.120033  0.347826  0.283334  0.193540  0.184087  0.506468
19  0.118721  0.271739  0.134378  0.174632  0.268371  0.718905
20  0.233496  0.206522  0.089137  0.182032  0.173026  0.861692
21  0.361564  0.228261  0.084296  0.268756  0.433333  0.899502
22  0.088493  0.239130  0.157989  0.290903  0.344549  0.333333
23  0.288584  0.293478  0.237046  0.174572  0.415937  0.499502
24  0.258540  0.184783  0.554443  0.131481  0.346001  0.462687
25  0.100814  0.065217  0.554579  0.183961  0.312871  0.782090
26  0.487486  0.336957  0.087225  0.685498  0.389372  0.867662
27  0.331094  0.391304  0.297733  0.334001  0.420727  0.188060
28  0.644817  0.413043  0.201254  0.203291  0.354338  0.407960
29  0.564355  0.380435  0.155395  0.196165  0.380447  0.752239
30  0.229998  0.467391  0.083590  0.083124  0.313144  0.730348
31  0.374880  0.217391  0.039227  0.153305  0.778390  0.838806
32  0.361227  0.239130  0.111980  0.240401  0.336177  0.883582
33  0.350893  0.315217  0.234239  0.222533  0.482103  0.889552
34  0.137291  0.152174  0.139411  0.246764  0.519729  0.458706
35  0.349334  0.391304  0.017452  0.152506  0.458019  0.780100
36  0.565217  0.543478  0.069784  0.138728  0.495332  0.793035
37  0.186585  0.402174  0.213475  0.260276  0.269924  0.751244
38  0.611512  0.489130  0.576461  0.209017  0.476785  0.454726
39  1.000000  0.576087  0.186930  0.247685  0.580725  0.684577
40  0.194482  0.217391  0.282864  0.256217  0.522029  0.483582
41  0.002670  1.000000  0.020922  0.000648  0.050747  0.823881
42  0.011309  1.000000  0.015380  0.003341  0.030363  0.738308

In [ ]:
df_new.min()

shop       0.000000
budget     0.000000
green      0.003959
share      0.000648
trans      0.001022
recycle    0.188060
dtype: float64

In [ ]:
df_new.max()

shop       1.000000
budget     1.000000
green      0.576461
share      1.000000
trans      0.778390
recycle    1.000000
dtype: float64

# 가중치 부여
- shop : 1.467
- green : 1.573
- share : 1.328
- trans : 1.481
- recycle : 1.732
- budget : 1.420

In [ ]:
# 기존 데이터 유지, 'df_result' 테이블 생성
df_result = df_new

In [ ]:
df_result.head()

       shop    budget     green     share     trans   recycle
0  0.000000  0.228261  0.003959  0.012744  0.007169  1.000000
1  0.021497  0.076087  0.083310  0.047338  0.069185  0.990050
2  0.001797  0.108696  0.053670  0.021047  0.009582  0.821891
3  0.054699  0.119565  0.128394  0.137024  0.001632  0.972139
4  0.028982  0.163043  0.132715  0.113008  0.018342  0.947264

In [ ]:
df_result['shop_rate'] = df_result['shop'] * 1.467
df_result['green_rate'] = df_result['green'] * 1.573
df_result['share_rate'] = df_result['share'] * 1.328
df_result['trans_rate'] = df_result['trans'] * 1.481
df_result['recycle_rate'] = df_result['recycle'] * 1.732
df_result['budget_rate'] = df_result['budget'] * 1.420
df_result.head()

       shop    budget     green  ...  trans_rate  recycle_rate  budget_rate
0  0.000000  0.228261  0.003959  ...    0.010618      1.732000     0.324130
1  0.021497  0.076087  0.083310  ...    0.102463      1.714766     0.108043
2  0.001797  0.108696  0.053670  ...    0.014191      1.423514     0.154348
3  0.054699  0.119565  0.128394  ...    0.002416      1.683745     0.169783
4  0.028982  0.163043  0.132715  ...    0.027164      1.640661     0.231522

[5 rows x 12 columns]

In [ ]:
# 필요 없는 행 삭제
df_result = df_result.drop(columns=['shop', 'budget', 'green', 'share', 'trans', 'recycle'])
df_result

    shop_rate  green_rate  share_rate  trans_rate  recycle_rate  budget_rate
0    0.000000    0.006228    0.016924    0.010618      1.732000     0.324130
1    0.031536    0.131047    0.062864    0.102463      1.714766     0.108043
2    0.002636    0.084423    0.027951    0.014191      1.423514     0.154348
3    0.080243    0.201963    0.181968    0.002416      1.683745     0.169783
4    0.042517    0.208761    0.150074    0.027164      1.640661     0.231522
5    0.130895    0.497412    0.231480    0.043584      1.623427     0.154348
6    0.147053    0.277797    0.034202    0.001514      1.644107     0.046304
7    0.036985    0.062530    0.108848    0.014379      1.668235     0.000000
8    0.009842    0.047615    0.059536    0.002348      1.694086     0.092609
9    0.008174    0.312822    0.067489    0.170048      1.697532     0.123478
10   0.061115    0.533043    0.231729    0.011079      1.602746     0.493913
11   0.887833    0.139876    0.357329    0.075364      1.702702     0.154348
12   0.125852    0.179098    0.182796    0.083355      1.721660     0.108043
13   0.013173    0.456383    0.117380    0.300762      1.713043     0.000000
14   0.546895    0.575509    1.328000    0.171422      1.394217     0.216087
15   0.135341    0.139762    0.172656    0.014241      1.547598     0.216087
16   0.828431    0.179364    0.171931    0.480287      1.266687     0.818043
17   0.295153    0.292414    0.259966    0.549956      1.413174     0.432174
18   0.176089    0.445684    0.257021    0.272633      0.877202     0.493913
19   0.174164    0.211376    0.231912    0.397457      1.245144     0.385870
20   0.342539    0.140212    0.241739    0.256251      1.492450     0.293261
21   0.530415    0.132598    0.356908    0.641766      1.557938     0.324130
22   0.129819    0.248517    0.386319    0.510276      0.577333     0.339565
23   0.423353    0.372873    0.231832    0.616003      0.865138     0.416739
24   0.379278    0.872139    0.174607    0.512427      0.801373     0.262391
25   0.147894    0.872353    0.244300    0.463362      1.354579     0.092609
26   0.715142    0.137205    0.910342    0.576659      1.502790     0.478478
27   0.485715    0.468335    0.443553    0.623097      0.325719     0.555652
28   0.945947    0.316572    0.269971    0.524774      0.706587     0.586522
29   0.827910    0.244437    0.260507    0.563441      1.302878     0.540217
30   0.337407    0.131487    0.110389    0.463766      1.264963     0.663696
31   0.549949    0.061705    0.203588    1.152796      1.452812     0.308696
32   0.529919    0.176145    0.319252    0.497878      1.530364     0.339565
33   0.514760    0.368458    0.295523    0.713995      1.540704     0.447609
34   0.201406    0.219294    0.327703    0.769719      0.794480     0.216087
35   0.512473    0.027452    0.202528    0.678326      1.351132     0.555652
36   0.829173    0.109770    0.184231    0.733587      1.373536     0.771739
37   0.273721    0.335796    0.345647    0.399758      1.301154     0.571087
38   0.897088    0.906774    0.277574    0.706118      0.787586     0.694565
39   1.467000    0.294041    0.328926    0.860053      1.185688     0.818043
40   0.285305    0.444945    0.340256    0.773125      0.837564     0.308696
41   0.003917    0.032911    0.000861    0.075156      1.426961     1.420000
42   0.016590    0.024192    0.004436    0.044968      1.278750     1.420000

# 최종 점수 계산

In [ ]:
df_result['total'] = (df_result['shop_rate'] + df_result['green_rate'] + df_result['share_rate'] + df_result['trans_rate'] + df_result['recycle_rate'] + df_result['budget_rate'] ) / 6
df_result

    shop_rate  green_rate  share_rate  ...  recycle_rate  budget_rate     total
0    0.000000    0.006228    0.016924  ...      1.732000     0.324130  0.348317
1    0.031536    0.131047    0.062864  ...      1.714766     0.108043  0.358453
2    0.002636    0.084423    0.027951  ...      1.423514     0.154348  0.284510
3    0.080243    0.201963    0.181968  ...      1.683745     0.169783  0.386686
4    0.042517    0.208761    0.150074  ...      1.640661     0.231522  0.383450
5    0.130895    0.497412    0.231480  ...      1.623427     0.154348  0.446857
6    0.147053    0.277797    0.034202  ...      1.644107     0.046304  0.358496
7    0.036985    0.062530    0.108848  ...      1.668235     0.000000  0.315163
8    0.009842    0.047615    0.059536  ...      1.694086     0.092609  0.317673
9    0.008174    0.312822    0.067489  ...      1.697532     0.123478  0.396590
10   0.061115    0.533043    0.231729  ...      1.602746     0.493913  0.488937
11   0.887833    0.139876    0.357329  ...      1.702702     0.154348  0.552909
12   0.125852    0.179098    0.182796  ...      1.721660     0.108043  0.400134
13   0.013173    0.456383    0.117380  ...      1.713043     0.000000  0.433457
14   0.546895    0.575509    1.328000  ...      1.394217     0.216087  0.705355
15   0.135341    0.139762    0.172656  ...      1.547598     0.216087  0.370947
16   0.828431    0.179364    0.171931  ...      1.266687     0.818043  0.624124
17   0.295153    0.292414    0.259966  ...      1.413174     0.432174  0.540473
18   0.176089    0.445684    0.257021  ...      0.877202     0.493913  0.420424
19   0.174164    0.211376    0.231912  ...      1.245144     0.385870  0.440987
20   0.342539    0.140212    0.241739  ...      1.492450     0.293261  0.461075
21   0.530415    0.132598    0.356908  ...      1.557938     0.324130  0.590626
22   0.129819    0.248517    0.386319  ...      0.577333     0.339565  0.365305
23   0.423353    0.372873    0.231832  ...      0.865138     0.416739  0.487656
24   0.379278    0.872139    0.174607  ...      0.801373     0.262391  0.500369
25   0.147894    0.872353    0.244300  ...      1.354579     0.092609  0.529183
26   0.715142    0.137205    0.910342  ...      1.502790     0.478478  0.720103
27   0.485715    0.468335    0.443553  ...      0.325719     0.555652  0.483678
28   0.945947    0.316572    0.269971  ...      0.706587     0.586522  0.558396
29   0.827910    0.244437    0.260507  ...      1.302878     0.540217  0.623232
30   0.337407    0.131487    0.110389  ...      1.264963     0.663696  0.495285
31   0.549949    0.061705    0.203588  ...      1.452812     0.308696  0.621591
32   0.529919    0.176145    0.319252  ...      1.530364     0.339565  0.565521
33   0.514760    0.368458    0.295523  ...      1.540704     0.447609  0.646841
34   0.201406    0.219294    0.327703  ...      0.794480     0.216087  0.421448
35   0.512473    0.027452    0.202528  ...      1.351132     0.555652  0.554594
36   0.829173    0.109770    0.184231  ...      1.373536     0.771739  0.667006
37   0.273721    0.335796    0.345647  ...      1.301154     0.571087  0.537860
38   0.897088    0.906774    0.277574  ...      0.787586     0.694565  0.711617
39   1.467000    0.294041    0.328926  ...      1.185688     0.818043  0.825625
40   0.285305    0.444945    0.340256  ...      0.837564     0.308696  0.498315
41   0.003917    0.032911    0.000861  ...      1.426961     1.420000  0.493301
42   0.016590    0.024192    0.004436  ...      1.278750     1.420000  0.464823

[43 rows x 7 columns]

# 파일 저장

## 인덱스 추가

In [ ]:
df_result['district'] = ['부산광역시 강서구', '부산광역시 금정구', '부산광역시 기장군', '부산광역시 남구', '부산광역시 동구', '부산광역시 동래구', 
'부산광역시 부산진구', '부산광역시 북구', '부산광역시 사상구', '부산광역시 사하구', '부산광역시 서구', '부산광역시 수영구', 
'부산광역시 연제구', '부산광역시 영도구', '부산광역시 중구', '부산광역시 해운대구', 
'서울특별시 강남구', '서울특별시 강동구', '서울특별시 강북구', '서울특별시 강서구', '서울특별시 관악구', '서울특별시 광진구', 
'서울특별시 구로구', '서울특별시 금천구', '서울특별시 노원구', '서울특별시 도봉구', '서울특별시 동대문구', '서울특별시 동작구', 
'서울특별시 마포구', '서울특별시 서대문구', '서울특별시 서초구', '서울특별시 성동구', '서울특별시 성북구', '서울특별시 송파구', 
'서울특별시 양천구', '서울특별시 영등포구', '서울특별시 용산구', '서울특별시 은평구', '서울특별시 종로구', '서울특별시 중구', 
'서울특별시 중랑구', 
'제주특별자치도 서귀포시', '제주특별자치도 제주시']

In [ ]:
df_result = df_result.set_index('district', drop = True)

In [ ]:
df_result

              shop_rate  green_rate  ...  budget_rate     total
district                             ...
부산광역시 강서구      0.000000    0.006228  ...     0.324130  0.348317
부산광역시 금정구      0.031536    0.131047  ...     0.108043  0.358453
부산광역시 기장군      0.002636    0.084423  ...     0.154348  0.284510
부산광역시 남구       0.080243    0.201963  ...     0.169783  0.386686
부산광역시 동구       0.042517    0.208761  ...     0.231522  0.383450
부산광역시 동래구      0.130895    0.497412  ...     0.154348  0.446857
부산광역시 부산진구     0.147053    0.277797  ...     0.046304  0.358496
부산광역시 북구       0.036985    0.062530  ...     0.000000  0.315163
부산광역시 사상구      0.009842    0.047615  ...     0.092609  0.317673
부산광역시 사하구      0.008174    0.312822  ...     0.123478  0.396590
부산광역시 서구       0.061115    0.533043  ...     0.493913  0.488937
부산광역시 수영구      0.887833    0.139876  ...     0.154348  0.552909
부산광역시 연제구      0.125852    0.179098  ...     0.108043  0.400134
부산광역시 영도구      0.013173    0.456383  ...     0.000000  0.433457
부산광역시 중구       0.546895    0.575509  ...     0.216087  0.705355
부산광역시 해운대구     0.135341    0.139762  ...     0.216087  0.370947
서울특별시 강남구      0.828431    0.179364  ...     0.818043  0.624124
서울특별시 강동구      0.295153    0.292414  ...     0.432174  0.540473
서울특별시 강북구      0.176089    0.445684  ...     0.493913  0.420424
서울특별시 강서구      0.174164    0.211376  ...     0.385870  0.440987
서울특별시 관악구      0.342539    0.140212  ...     0.293261  0.461075
서울특별시 광진구      0.530415    0.132598  ...     0.324130  0.590626
서울특별시 구로구      0.129819    0.248517  ...     0.339565  0.365305
서울특별시 금천구      0.423353    0.372873  ...     0.416739  0.487656
서울특별시 노원구      0.379278    0.872139  ...     0.262391  0.500369
서울특별시 도봉구      0.147894    0.872353  ...     0.092609  0.529183
서울특별시 동대문구     0.715142    0.137205  ...     0.478478  0.720103
서울특별시 동작구      0.485715    0.468335  ...     0.555652  0.483678
서울특별시 마포구      0.945947    0.316572  ...     0.586522  0.558396
서울특별시 서대문구     0.827910    0.244437  ...     0.540217  0.623232
서울특별시 서초구      0.337407    0.131487  ...     0.663696  0.495285
서울특별시 성동구      0.549949    0.061705  ...     0.308696  0.621591
서울특별시 성북구      0.529919    0.176145  ...     0.339565  0.565521
서울특별시 송파구      0.514760    0.368458  ...     0.447609  0.646841
서울특별시 양천구      0.201406    0.219294  ...     0.216087  0.421448
서울특별시 영등포구     0.512473    0.027452  ...     0.555652  0.554594
서울특별시 용산구      0.829173    0.109770  ...     0.771739  0.667006
서울특별시 은평구      0.273721    0.335796  ...     0.571087  0.537860
서울특별시 종로구      0.897088    0.906774  ...     0.694565  0.711617
서울특별시 중구       1.467000    0.294041  ...     0.818043  0.825625
서울특별시 중랑구      0.285305    0.444945  ...     0.308696  0.498315
제주특별자치도 서귀포시   0.003917    0.032911  ...     1.420000  0.493301
제주특별자치도 제주시    0.016590    0.024192  ...     1.420000  0.464823

[43 rows x 7 columns]

In [ ]:
# 불필요한 열 삭제 ('_rate'데이터는 가중치 부여한 값임)
df_new = df_new.drop(columns=['shop_rate', 'budget_rate', 'green_rate', 'share_rate', 'trans_rate', 'recycle_rate'])

In [ ]:
df_new['district'] = ['부산광역시 강서구', '부산광역시 금정구', '부산광역시 기장군', '부산광역시 남구', '부산광역시 동구', '부산광역시 동래구', 
'부산광역시 부산진구', '부산광역시 북구', '부산광역시 사상구', '부산광역시 사하구', '부산광역시 서구', '부산광역시 수영구', 
'부산광역시 연제구', '부산광역시 영도구', '부산광역시 중구', '부산광역시 해운대구', 
'서울특별시 강남구', '서울특별시 강동구', '서울특별시 강북구', '서울특별시 강서구', '서울특별시 관악구', '서울특별시 광진구', 
'서울특별시 구로구', '서울특별시 금천구', '서울특별시 노원구', '서울특별시 도봉구', '서울특별시 동대문구', '서울특별시 동작구', 
'서울특별시 마포구', '서울특별시 서대문구', '서울특별시 서초구', '서울특별시 성동구', '서울특별시 성북구', '서울특별시 송파구', 
'서울특별시 양천구', '서울특별시 영등포구', '서울특별시 용산구', '서울특별시 은평구', '서울특별시 종로구', '서울특별시 중구', 
'서울특별시 중랑구', 
'제주특별자치도 서귀포시', '제주특별자치도 제주시']

In [ ]:
df_new = df_new.set_index('district', drop = True)

In [ ]:
df_new

                  shop    budget     green     share     trans   recycle
district
부산광역시 강서구     0.000000  0.228261  0.003959  0.012744  0.007169  1.000000
부산광역시 금정구     0.021497  0.076087  0.083310  0.047338  0.069185  0.990050
부산광역시 기장군     0.001797  0.108696  0.053670  0.021047  0.009582  0.821891
부산광역시 남구      0.054699  0.119565  0.128394  0.137024  0.001632  0.972139
부산광역시 동구      0.028982  0.163043  0.132715  0.113008  0.018342  0.947264
부산광역시 동래구     0.089226  0.108696  0.316219  0.174307  0.029428  0.937313
부산광역시 부산진구    0.100240  0.032609  0.176603  0.025754  0.001022  0.949254
부산광역시 북구      0.025212  0.000000  0.039752  0.081964  0.009709  0.963184
부산광역시 사상구     0.006709  0.065217  0.030270  0.044832  0.001586  0.978109
부산광역시 사하구     0.005572  0.086957  0.198870  0.050820  0.114819  0.980100
부산광역시 서구      0.041660  0.347826  0.338870  0.174494  0.007481  0.925373
부산광역시 수영구     0.605203  0.108696  0.088923  0.269073  0.050887  0.983085
부산광역시 연제구     0.085789  0.076087  0.113858  0.137648  0.056283  0.994030
부산광역시 영도구     0.008980  0.000000  0.290135  0.088388  0.203080  0.989055
부산광역시 중구      0.372798  0.152174  0.365867  1.000000  0.115747  0.804975
부산광역시 해운대구    0.092257  0.152174  0.088851  0.130012  0.009616  0.893532
서울특별시 강남구     0.564711  0.576087  0.114026  0.129466  0.324299  0.731343
서울특별시 강동구     0.201195  0.304348  0.185896  0.195757  0.371341  0.815920
서울특별시 강북구     0.120033  0.347826  0.283334  0.193540  0.184087  0.506468
서울특별시 강서구     0.118721  0.271739  0.134378  0.174632  0.268371  0.718905
서울특별시 관악구     0.233496  0.206522  0.089137  0.182032  0.173026  0.861692
서울특별시 광진구     0.361564  0.228261  0.084296  0.268756  0.433333  0.899502
서울특별시 구로구     0.088493  0.239130  0.157989  0.290903  0.344549  0.333333
서울특별시 금천구     0.288584  0.293478  0.237046  0.174572  0.415937  0.499502
서울특별시 노원구     0.258540  0.184783  0.554443  0.131481  0.346001  0.462687
서울특별시 도봉구     0.100814  0.065217  0.554579  0.183961  0.312871  0.782090
서울특별시 동대문구    0.487486  0.336957  0.087225  0.685498  0.389372  0.867662
서울특별시 동작구     0.331094  0.391304  0.297733  0.334001  0.420727  0.188060
서울특별시 마포구     0.644817  0.413043  0.201254  0.203291  0.354338  0.407960
서울특별시 서대문구    0.564355  0.380435  0.155395  0.196165  0.380447  0.752239
서울특별시 서초구     0.229998  0.467391  0.083590  0.083124  0.313144  0.730348
서울특별시 성동구     0.374880  0.217391  0.039227  0.153305  0.778390  0.838806
서울특별시 성북구     0.361227  0.239130  0.111980  0.240401  0.336177  0.883582
서울특별시 송파구     0.350893  0.315217  0.234239  0.222533  0.482103  0.889552
서울특별시 양천구     0.137291  0.152174  0.139411  0.246764  0.519729  0.458706
서울특별시 영등포구    0.349334  0.391304  0.017452  0.152506  0.458019  0.780100
서울특별시 용산구     0.565217  0.543478  0.069784  0.138728  0.495332  0.793035
서울특별시 은평구     0.186585  0.402174  0.213475  0.260276  0.269924  0.751244
서울특별시 종로구     0.611512  0.489130  0.576461  0.209017  0.476785  0.454726
서울특별시 중구      1.000000  0.576087  0.186930  0.247685  0.580725  0.684577
서울특별시 중랑구     0.194482  0.217391  0.282864  0.256217  0.522029  0.483582
제주특별자치도 서귀포시  0.002670  1.000000  0.020922  0.000648  0.050747  0.823881
제주특별자치도 제주시   0.011309  1.000000  0.015380  0.003341  0.030363  0.738308

## 다운로드

In [ ]:
# 가중치 계산 이후 카테고리별 + total 데이터
df_result.to_csv('final_rate_by_area.csv')

In [ ]:
# 가중치 계산 이전 카테고리별 데이터
df_new.to_csv('before_weighted_value.csv')